[[builders]]
host = "ssh-ng://fraktur"
systems = ["x86_64-linux"]
private_key = "~/.ssh/id_ed25519"
max_builds = 8
speed_factor = 1.0
features = ["kvm", "big-parallel"]
mandatory_features = []
public_key = ""
