---
on:
  pull_request:
  push:
    branches:
      - main

name: CI

jobs:
  check-flake:
    name: Check Nix flake (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            extra-experimental-features = nix-command flakes
            accept-flake-config = true

      - uses: cachix/cachix-action@v15
        with:
          name: 9999years
          authToken: '${{ secrets.CACHIX_TOKEN }}'

      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: nix flake check
        run: nix flake check --print-build-logs

      - name: nix develop
        run: nix develop --print-build-logs --command true

      - name: nix build
        run: nix build --print-build-logs

      - name: nix build (misc)
        run: |
          nix build --print-build-logs .#cargo
          nix build --print-build-logs .#get-crate-version
          nix build --print-build-logs .#make-release-commit
