---
# This workflow runs when PRs are merged and tags/builds/publishes a release.

# Run when PRs to main are closed.
on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Build and publish a release

jobs:
  build:
    name: Build user manual
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            extra-experimental-features = nix-command flakes
            accept-flake-config = true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build user manual
        run: |
          RESULT=$(nix build --no-link --print-out-paths --print-build-logs .#nix-remote.user-manual)
          cp -r "$RESULT/share/nix-remote/html-manual" nix-remote-user-manual

      - name: Upload GitHub Pages assets
        uses: actions/upload-pages-artifact@v3
        with:
          path: nix-remote-user-manual/


  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
